---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    postgres-password: AgDGDucgv4zPuP995r6N0Z+vGch4G6Afw313yF9srUXH8UjsWTVQgFUs9QODFgcm2NAsb+loUtG9Znf2TtjZgOXgrmlOagKjj77IlWOPTbBvWd4ajN3JHBIZOLgW9QZzO8hs2GdlH+HLNCB8G162S/AJhk4fh0fMvv6X0oypnsSG1Ixs2G8TWqX+t/i9gE2HyvDsDEYhEeFXBAVdof6dDGYjPVFWQVbQuiIGHzNrXtKUdDhXbNK2yOIM1Iyf0JpgQO12U35h8o6v70B+MgKn/rU/Yo7J5AtyMwJcbMukqHwJ0ViKu8Yv76f5y3UaR6FXMkxCJu6F8trRUlBQX9QN+YkuZW9x8krhzOU/D1AKSvbJE1jp7FRdrYjgfex6bYhA3e+bhkZxb28EwrAdXtFmI/Te/I5Gg9X07W8DyvzZflyx1cCHqdnZVDbjDPgfh99GZXuVOODyPRqYM2ijd32MU4CL3OxOg9eLPHSvyn9iRThyhzARcHwcQUhhh90b/DOZids5C7lmDw+RQfCu9TiqVOA1mlHV0wCrXq1SYitLthywzYVtND0vQebYSu/vZ+6j5PPaQ6JGpijFgNiK4bsQ+kEmbvfEcwU4KNsaNuKb/e/oOWBPhtPCD2DfdP6trCObO/sKu1cTeTjvLSZOLRwMfibIhvpLa/DOGEhmKq1pz9HBLnFqy9XIt9w3m5YAq3KPuNrCr7N2vAs64J7AXsv/WrPpeAmCddpKfVE=
    redis-password: AgCVQ32Xf3XGR1oAJYGsWHXIun6H6zWj0RBw1Uv27DPZHC1MHc0dnJP56heOhcmQMZsOXapQSQTa7uK9hEKq5oa0kINnnSnSN1UgPbCHFPJj8bOKsv1y/YlrRU9wNFbjtZw65qXU1/7HwZl/kOH5s8Odmv7yN8qa3HH0kbvUs4QJk+L0uep7EQj8TQLkhxK05k1qIl20P5/J9Ji69hxJZgxf2sgaEmrXPxqHxoQwtduhtEqNqUb02TXSvjlDSCIdtXzkf3xMd4spPv10BdiHIggwmS7S8Aig+bd2ph1YW8ICJs7T0pBmol/MOeR9Fvx0etIVfnk6qpVqQjdr0GWBpOpWpHh3LQi3WRxDplBeeNgrKpMeGyH0/1fCR3Wl4XH5DFZUrEgmbGtT+CxrbtltARJ+6jahn5odeLWBdyWU8/vQBnWU0P2mgBXJ/HazO4HzOIKCswc5TqWe0ojo2y3/RlgfaWMZwrOGDx0vPMG23J+L7/rQpguBXNGLCT3pxorFjSru1sw5SZgLDijI9HnQNQETDlOKW8wSKrw9abMdLyXJVv3b2vZNlup+8joXFfU3RMJb+OYvWY2heBd4DhcjSNgRXdRSPjrGKWzXowxQv+rR3QcrsDNy/orKELZ8MChjiKqmFEs+i6ONZeR/jcMb+gvH3MIi3QNQj46HNqZfIvtiORCpMRfuu28AC8ePKaEDdRoDayapOBs3qQW16LVOcvOFEHs15Kksa+XVig==
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: default
    type: Opaque
