---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: databases
spec:
  encryptedData:
    postgres-password: AgBGa+mMO5mAHWjUIyCkA15ll3R3hHWPHIS+Zdb6+6paG9WaxGfSG6jmIRuH+veHOaKodmG1I58wFRHmYljlhoIjIPRX6RawiDO9hv7sT0+W/XKqpH5W+ZtbcU+S2hv6J97a2MxH1s82C61x0AbGlufzTHh94tcVflfT+15t6sZE/W1vhlzDezdNZ97aaOeCVnEXAUYRFQNGA/2dOxtQtFFKG+EDp7EBZIzYiIrK8WdTuffj53yXw3jOlmO6w3XbQHqjtZlTPsFzV8aiOGxVQHhe4If69c9OaS+fgQ/XAXFzToEk9iNtLgQeELLODf0iZ8+nTm8m4jjjzYV/IS5RUn/N46/2X1vbUT+3mmBLYLlH7Z735rNpC7xCaInHUDIvcnHPh/THmu+i8g+sQo2+hk7rK6gxrxbMB2v97z0oA467T7SD3kURNmeMrZ2pCQL1sa0ue9Nw1pfpXX13unHOFEj08dqY6FSOmJFup/srUwN0GyNBZTPPWTGO6HU0oxcFvj14W8M8ZGAD6/08zwXk9Y28cdoqRf+NOhfnVL7vNn6CptxGd6OwUv3PINGRnF7Cl5bmBsWO54SOCI3fAgsWcVacFqMVbYEF7xEHJC3SYADH/BRBNseZrFP9MUPV+LsUDNW/K7meZWR8HZMJMeQ9A4zMgv+1L3Gcg753NdR3xnRZPGLjEUMuNBJYI8qQYn19Nb4lnVEgeIXwibOe4vag1+Ts/wpijjjZCC4=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: databases
    type: Opaque
