apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/hjali7/loopchat.git
    targetRevision: main
    path: infra/k8s/databases/postgres
    
  destination:
    server: https://kubernetes.default.svc
    namespace: databases

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true