---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: databases
spec:
  encryptedData:
    redis-password: AgBRKoibCWS+cpbOPUYHOevDHFJmjFbpqgKC8427X45P1ipB9hqLAhfF7myVvEG9EOg/tNU5Af7NJTHYbmuG8eKqaJ82YQ48l/8lkYNueAHGeQ/QmigzPDGcN8UsWkvCcUWIkUtI9VuIqHDiCAAOzZUOKS50Y7pOExBpU5L9PCp4+mHO3IlLtseDb4YeAhm4wARCIQY1EeykFzciIXpRqXe+CWI7M6LdqOhEf0zB4b7SarSMnNYF4Zn0ulJrxKkI7pP5R7sBQ8CzipG6rFwmYrqjzsMeF1xI/a9K6iabuiBeK0snhLbiX5012DsrBfDeHbFjr2mEUNUbCbG1MrhlficnD4pOnCQeiajxbcUWiyOgAUhZKaqcis+34rfIPJGSItgH/5AsIV67CPINHeSNeU2ffZNSOyF1Xo9W9gWNL6OnRh1kCeuE/GCYBIUqXfVDexsLeHUZzGjbyfzFFc2Mv7HtE9BTlugUh+j/8LPcymNCobbT53FxCU8JrVBXQS5Ccb64cWhnqhlE80QMRnVGUxhXVTq8h8PvA3eT0Yt9CFwTJZ1HVawe3Y87djqOskC4LoEdqXzSzdkN2ue7H5ELSr6qBK28lLKZkcycQOBFKp25EiTSBAVvI8wgv1UeRisxFrv9nKyq49DIOUSK0Ruii70uRJgQFB+oZIj1BNseh2+qJPhogmoCoQ9Cg4WEMUO6CkiZpnvmWF/C94L3HROLl52vbbutrkZsWjggAg==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: databases
    type: Opaque
