---

- name: Install k3s Cluster
  hosts: all
  become: yes
  vars:
    k3s_version: "v1.29.1+k3s2"

  tasks:
    - name: Download k3s install script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0700'

    - name: Install k3s (Master Node)
      shell: /tmp/k3s_install.sh
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        INSTALL_K3S_EXEC: "server --disable traefik --write-kubeconfig-mode 644"
      args:
        creates: /usr/local/bin/k3s
      
    - name: Ensure k3s service is running
      service:
        name: k3s
        state: started
        enabled: true
    
    - name: Fetch kubeconfig to local machine
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/loopchat.yaml
        flat: yes
